version: 2.1

jobs:
  test:
    docker:
      - image: gcr.io/bazel-public/bazel:5.4.0
    steps:
      - checkout
      - run:
          command: bazel test //...
      - run:
          command: bazel test //...
          working_directory: examples/simple

workflows:
  test-workflow:
    jobs:
      - test
